### ISSUE TITLE
Consider migrating to Docz

### ISSUE THREAD

**Issue by amcgee** [dhis2/cli-utils-docsite#60]
The [Docz](https://www.docz.site) tool seems offer some functionality we'd like in our documentation - namely live-editable previews and PropType parsing, both in [MDX (JSX in Markdown)](https://github.com/mdx-js/mdx) for human-readable descriptions and layouts.  This might make it an attractive drop-in replacement for [docsify](https://docsify.js.org) which we currently use.

See also #59, https://github.com/dhis2/ui/issues/136, https://github.com/dhis2/ui/issues/135

**Comment by HendrikThePendric** [comment]
To me the most fundamental problem with our current documentation setup is that the vast majority of our jsDoc comments just duplicates the information that is in the propTypes declarations. Since these comments are created/updated manually, the process is very prone to error and/or the docs becoming out-of-date. Since Docz can [generate documentation from `propTypes` declarations](https://www.docz.site/docs/built-in-components#component-props), this would be a good candidate IMO.

**Comment by amcgee** [comment]
I believe this was explored previously by myself (faulty memory) and/or @varl, it would serve a similar purpose but require a bit more wiring.  It also doesn't support, for example, Typescript or externally-defined props definitions since it does static analysis.

https://github.com/reactjs/react-docgen

**Comment by varl** [comment]
Superseded by https://jira.dhis2.org/browse/CLI-3.
